"""
Keyword retrieval RAG README generator.
Fully free (no embeddings).
"""

import os, json, re
from pathlib import Path
import requests
from datetime import datetime

API_KEY = os.environ["OPENROUTER_API_KEY"]
CHAT_URL = "https://openrouter.ai/api/v1/chat/completions"

files = json.loads(Path(".repo_index/files.json").read_text())

KEYWORDS = [
    "main", "start", "run", "listen", "port",
    "docker", "build", "install", "config",
    "server", "client", "database", "redis",
    "kubernetes", "compose", "cmake", "npm"
]

def score(text):
    text = text.lower()
    return sum(text.count(k) for k in KEYWORDS)

top = sorted(files.items(), key=lambda x: -score(x[1]))[:8]

context = ""
for path, txt in top:
    context += f"\nFILE: {path}\n{txt[:3000]}\n"

payload = {
 "model": "openrouter/free",
 "messages": [
   {"role":"system","content":"Write a markdown GitHub README (just write, not generate the file!) using ONLY provided files. Do not hallucinate."},
   {"role":"user","content":context}
 ]
}

r = requests.post(CHAT_URL,
    headers={"Authorization":f"Bearer {API_KEY}"},
    json=payload,
    timeout=120
)
r.raise_for_status()
data = r.json()

readme = data["choices"][0]["message"]["content"]
model = data.get("model","unknown")

header=f"""⚠️ This README was automatically generated by AI (keyword-retrieval RAG → OpenRouter → LLM) every push to main via Actions and may be inaccurate.
Model: {model}
Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

---
"""

Path("README.md").write_text(header+readme.strip()+"\n")
