"""
Retrieves relevant project files and generates README.
"""

import os, json, numpy as np
from pathlib import Path
import requests
from datetime import datetime

API_KEY = os.environ["OPENROUTER_API_KEY"]
CHAT_URL = "https://openrouter.ai/api/v1/chat/completions"
EMBED_URL = "https://openrouter.ai/api/v1/embeddings"

embeddings = json.loads(Path(".repo_index/embeddings.json").read_text())


def embed_query(text):
    r = requests.post(
        EMBED_URL,
        headers={"Authorization": f"Bearer {API_KEY}"},
        json={"model":"openrouter/embedding","input":text},
        timeout=60
    )
    r.raise_for_status()
    return r.json()["data"][0]["embedding"]


def sim(a,b):
    a=np.array(a); b=np.array(b)
    return float(np.dot(a,b)/(np.linalg.norm(a)*np.linalg.norm(b)))


query = embed_query("How to build run and understand this project")

top = sorted(embeddings.items(), key=lambda x:-sim(query,x[1]))[:8]

context=""
for path,_ in top:
    context += f"\nFILE: {path}\n"
    context += Path(path).read_text(errors="ignore")[:3000] + "\n"


payload={
 "model":"openrouter/free",
 "messages":[
   {"role":"system","content":"Write a GitHub README using ONLY provided files. Do not hallucinate."},
   {"role":"user","content":context}
 ]
}

r=requests.post(CHAT_URL,headers={"Authorization":f"Bearer {API_KEY}"},json=payload,timeout=120)
r.raise_for_status()
data=r.json()

readme=data["choices"][0]["message"]["content"]
model=data.get("model","unknown")

header=f"""⚠️ This README was automatically generated by AI and may be inaccurate.
Model: {model}
Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

---
"""

Path("README.md").write_text(header+readme.strip()+"\n")
