\
SHELL := /usr/bin/env bash

.PHONY: \
	server-setup server-teardown server-up server-down \
	worker-setup worker-teardown worker-up worker-down

server-setup:
	./scripts/server-setup.sh

server-up:
	./scripts/server-up.sh

server-down:
	./scripts/server-down.sh

server-teardown:
	./scripts/server-teardown.sh

worker-setup:
	./scripts/worker-setup.sh

worker-up:
	./scripts/worker-up.sh

worker-down:
	./scripts/worker-down.sh

worker-teardown:
	./scripts/worker-teardown.sh
