apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../observability
  - service-account.yaml

configMapGenerator:
  - name: grafana-provisioning
    namespace: tcp-lab
    behavior: merge
    files:
      - datasource.yaml
  - name: grafana-dashboard
    namespace: tcp-lab
    behavior: merge
    files:
      - elasticache-serverless.json=elasticache-serverless.json

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: grafana-service-account-patch.yaml
