# Applied by default with make tcp-demo. Scales tcp-demo replicas by CPU (1–10 pods).
# Requires metrics-server in the cluster (kind: often present; minikube: minikube addons enable metrics-server).
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tcp-demo
  namespace: tcp-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tcp-demo
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
