apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: gateway-cpu
  namespace: tcp-lab
spec:
  template:
    metadata:
      labels:
        app: tcp-server-autoscaler
        autoscaling-target: gateway
    spec:
      containers:
        - name: autoscaler
          image: tcp-server-autoscaler:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: CPU_REQUEST_MILLICORES
              value: "250"
            - name: PROMETHEUS_URL
              value: http://prometheus.tcp-lab.svc.cluster.local:9090
            - name: TARGET_POD_PATTERN
              value: gateway-.*
            - name: TARGET_CONTAINER
              value: gateway
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  config:
    - name: interval
      value: "15000"
