apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - server-headless-service.yaml
  - server-schema-job.yaml
  - server-deployment.yaml
  - server-autoscaler.yaml
  - gateway-deployment.yaml
  - gateway-hpa.yaml
  - gateway-service.yaml
  - gateway-stats-service.yaml
  - pod-disruption-budgets.yaml
