apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway
  namespace: tcp-lab
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tcp-server
  namespace: tcp-lab
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: tcp-server
