apiVersion: v1
kind: Service
metadata:
  name: tcp-server-discovery
  namespace: tcp-lab
spec:
  clusterIP: None
  selector:
    app: tcp-server
  ports:
    - name: tcp
      protocol: TCP
      port: 7000
      targetPort: tcp
