apiVersion: v1
kind: Secret
metadata:
  name: tcp-server-databases
  namespace: tcp-lab
type: Opaque
stringData:
  postgres-user: tcp_lab
  postgres-password: tcp_lab_local
  postgres-database: tcp_lab
  postgres-dsn: postgres://tcp_lab:tcp_lab_local@postgres.tcp-lab.svc.cluster.local:5432/tcp_lab?sslmode=disable
  redis-addr: redis.tcp-lab.svc.cluster.local:6379
