apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: tcp-lab
spec:
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 9000
      targetPort: tcp
      nodePort: 30000
