apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - valkey-secret.yaml
  - valkey-service.yaml
  - valkey-cluster.yaml
  - valkey-shard-autoscaler.yaml
patches:
  - path: gateway-nodeport-patch.yaml
  - path: stats-nodeport-patch.yaml
  - path: autoscaler-fast-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      namespace: tcp-lab
      labelSelector: app=tcp-server-autoscaler
  - path: autoscaler-fast-env-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      namespace: tcp-lab
      labelSelector: app=tcp-server-autoscaler
