apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - database-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - redis-service.yaml
  - redis-deployment.yaml
patches:
  - path: gateway-nodeport-patch.yaml
  - path: stats-nodeport-patch.yaml
  - path: gateway-hpa-fast-patch.yaml
  - path: server-autoscaler-fast-patch.yaml
