"""
Minimal deterministic README generator.

Design:
- Scan repo for important files
- Provide evidence to LLM
- Generate README
- Add AI disclosure header

Uses OpenRouter free model.
"""

import os
import requests
from pathlib import Path
from datetime import datetime

API_KEY = os.environ["OPENROUTER_API_KEY"]
API_URL = "https://openrouter.ai/api/v1/chat/completions"


# -------- Repo scanning --------

IMPORTANT_FILES = [
    "package.json",
    "pyproject.toml",
    "requirements.txt",
    "Cargo.toml",
    "go.mod",
    "CMakeLists.txt",
    "Dockerfile",
    "docker-compose.yml",
]

CODE_EXTENSIONS = {".py",".js",".ts",".cpp",".c",".cs",".rs",".go",".java"}


def read_file(path, limit=3000):
    try:
        return Path(path).read_text(errors="ignore")[:limit]
    except:
        return ""


def collect_context():
    context = []

    # include important root files
    for f in IMPORTANT_FILES:
        if Path(f).exists():
            context.append(f"\nFILE: {f}\n{read_file(f)}")

    # include a few representative source files
    for file in Path(".").rglob("*"):
        if file.suffix.lower() in CODE_EXTENSIONS:
            context.append(f"\nFILE: {file}\n{read_file(file)}")
        if len(context) > 12:
            break

    return "\n".join(context)


# -------- LLM call --------

def call_llm(context):
    payload = {
        "model": "openrouter/free",
        "temperature": 0.2,
        "messages": [
            {
                "role": "system",
                "content": (
                    "Write a concise accurate GitHub README using ONLY the provided files. "
                    "Do not invent commands. If unsure, say TBD."
                ),
            },
            {"role": "user", "content": context},
        ],
    }

    r = requests.post(
        API_URL,
        headers={"Authorization": f"Bearer {API_KEY}"},
        json=payload,
        timeout=120,
    )
    r.raise_for_status()
    return r.json()


# -------- Write README --------

def write_readme(response):
    content = response["choices"][0]["message"]["content"]
    model = response.get("model", "unknown-model")

    header = f"""⚠️ This README was automatically generated by AI and may be inaccurate.
Model: {model}
Generated: {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

---
"""

    Path("README.md").write_text(header + content.strip() + "\n")


def main():
    context = collect_context()
    response = call_llm(context)
    write_readme(response)
    print("README generated")


if __name__ == "__main__":
    main()
