from pathlib import Path
import os

ROOT = Path(".")
DOCS = ROOT / "docs"

EXCLUDE_DIRS = {
    ".git","node_modules","build","bin","obj",".idea",".vs",
    "__pycache__",".pytest_cache",".venv","dist","out",".github"
}

SKIP_EXT = {
    ".png",".jpg",".jpeg",".gif",".dll",".exe",".pdb",".uasset",".umap",".zip",".7z",".gz"
}

def should_skip_dir(name):
    return name in EXCLUDE_DIRS

def should_skip_file(name):
    return any(name.endswith(ext) for ext in SKIP_EXT)

def scan():
    structure = {}

    for root, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if not should_skip_dir(d)]
        rel = Path(root).relative_to(ROOT)

        valid_files = [f for f in files if not should_skip_file(f)]
        if valid_files:
            structure[str(rel)] = sorted(valid_files)

    return structure


# ---------- PAGE: REPOSITORY MAP ----------
def write_repo_map(structure):
    lines = ["# Repository Map\n"]

    for folder in sorted(structure):
        lines.append(f"## {folder}\n")
        for f in structure[folder][:40]:
            lines.append(f"- {f}")
        lines.append("")

    (DOCS / "repository-map.md").write_text("\n".join(lines))


# ---------- PAGE: SCRIPTS DOC ----------
def write_scripts_doc(structure):
    lines = ["# Scripts Reference\n"]

    for folder, files in structure.items():
        if "script" in folder.lower() or "tools" in folder.lower():
            lines.append(f"## {folder}\n")
            for f in files:
                if f.endswith((".sh",".py",".ps1",".bat")):
                    lines.append(f"- `{f}`")
            lines.append("")

    (DOCS / "scripts.md").write_text("\n".join(lines))


# ---------- PAGE: INFRA SUMMARY ----------
def write_infra_doc(structure):
    lines = ["# Infrastructure Overview\n"]

    keywords = ("infra","k8","helm","terraform","kubernetes, src")

    for folder, files in structure.items():
        if any(k in folder.lower() for k in keywords):
            lines.append(f"## {folder}\n")
            for f in files:
                lines.append(f"- {f}")
            lines.append("")

    (DOCS / "infrastructure.md").write_text("\n".join(lines))


# ---------- README ----------
def write_readme(structure):
    lines = [
        "# K8 Local To Cloud Project",
        "",
        "This README is automatically generated by CI.",
        "",
        "## Key Directories",
        ""
    ]

    for folder in sorted(structure)[:12]:
        lines.append(f"- `{folder}`")

    lines += [
        "",
        "## Documentation",
        "Full documentation available on GitHub Pages.",
    ]

    Path("README.md").write_text("\n".join(lines))


def main():
    DOCS.mkdir(exist_ok=True)
    structure = scan()

    write_repo_map(structure)
    write_scripts_doc(structure)
    write_infra_doc(structure)
    write_readme(structure)


if __name__ == "__main__":
    main()
