- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: CPU_RATE_WINDOW
    value: "15s"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: EVALUATION_INTERVAL_SECONDS
    value: "5"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SCALE_UP_CPU_THRESHOLD
    value: "70"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SCALE_DOWN_STABILIZATION_EVALUATIONS
    value: "12"
