apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: gateway-loadbalancer-patch.yaml
  - path: gateway-spread-patch.yaml
  - path: server-spread-patch.yaml
